-- Add source column to objective_findings to distinguish LLM vs human-coded findings.
-- Values: 'llm' (generated by AI), 'human' (from manual DOCX coding), 'both' (matched).
-- Default 'llm' so existing rows are correctly tagged.

ALTER TABLE objective_findings
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'llm';

-- Index for filtering by source
CREATE INDEX IF NOT EXISTS idx_objective_findings_source ON objective_findings(source);
